09-implemented-shopping-cart-Cart-item
RostyslavOnysh/book-store pull request #9
Opened 2023-09-25 10:14 UTC by RostyslavOnysh

Hi,I check every methods, DELETE and PUT work perfectly.I get in POSTMAN status 200.But when I try to use GET methods I don't have any errors and in POSTMAN status provide that everything is okay and status 200. But response body is empty.And when I try to add new book to the shopping cart I get 401 status, and error  "10:48:35.803 [http-nio-8080-exec-4] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Cannot add or update a child row: a foreign key constraint fails (`springdatabase`.`cart_items`, CONSTRAINT `fk_cart_items_shopping_carts` FOREIGN KEY (`shopping_carts_id`) REFERENCES `shopping_carts` (`id`))
10:48:35.811 [http-nio-8080-exec-4] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/api].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Request processing failed: org.springframework.dao.DataIntegrityViolationException: could not execute statement [Cannot add or update a child row: a foreign key constraint fails (`springdatabase`.`cart_items`, CONSTRAINT `fk_cart_items_shopping_carts` FOREIGN KEY (`shopping_carts_id`) REFERENCES `shopping_carts` (`id`))] [insert into cart_items (books_id,is_deleted,quantity,shopping_carts_id) values (?,?,?,?)]; SQL [insert into cart_items (books_id,is_deleted,quantity,shopping_carts_id) values (?,?,?,?)]; constraint [null]] with root cause
java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`springdatabase`.`cart_items`, CONSTRAINT `fk_cart_items_shopping_carts` FOREIGN KEY (`shopping_carts_id`) REFERENCES `shopping_carts` (`id`))
"

2023-09-25 12:15 UTC, okuzan requested changes
It seems like there is a lot of work that needs to be done in the services. If your application is not functioning properly, it is recommended to post a thread in the chat section discussing the issue and then provide a working solution for review. Service methods should not be overly complex. Try delegating some of the work to mappers and utility methods in entities that are responsible for updating relationships.

2023-09-25 12:15 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/cartitem/impl/CartItemServiceImpl.java
> +    public CartItemResponseDto getAllCartItemsForShoppingCart(Long shoppingCartId,
I don't get what this method is for. For cart item service save,getById, and delete should be enough - these methods would be used in shopping cart service

2023-09-25 12:15 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/cartitem/impl/CartItemServiceImpl.java
> +        cartItem.setShoppingCart(shoppingCartRepository.getById(id));
use mapper to transform request dto to CartItem model

2023-09-25 12:15 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/shoppingcart/ShoppingCartService.java
> +
```suggestion
```

2023-09-25 12:15 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        }
bad practice

2023-09-25 12:15 UTC, okuzan commented on src/main/java/spring/boot/bookstore/repository/shoppingcart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> getUserById(Long id);
```suggestion
    Optional<ShoppingCart> getById(Long id);
```

2023-09-25 12:15 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/cartitem/impl/CartItemServiceImpl.java
> +        cartItem.setShoppingCart(shoppingCartRepository.getById(id));
foreign key constraint error may be occuring here - what if getById returns null?

2023-09-27 17:46 UTC, Ivan95kos requested changes
Please, fix the previous comments

2023-09-27 17:46 UTC, Ivan95kos commented on src/main/java/spring/boot/bookstore/repository/cartitem/CartItemRepository.java
> +    Set<CartItem> findCartItemByShoppingCartId(@Param("shoppingCartId") Long shoppingCart);
such simple queries should be handled by proper method naming, please recheck work without them and fix just naming method if required

2023-09-27 17:46 UTC, Ivan95kos commented on src/main/java/spring/boot/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +
not fixed

2023-09-27 17:46 UTC, Ivan95kos commented on src/main/java/spring/boot/bookstore/service/cartitem/impl/CartItemServiceImpl.java
> +
not fixed

2023-09-27 17:46 UTC, Ivan95kos commented on src/main/java/spring/boot/bookstore/repository/BookRepository.java
> +    List<Book> findByCategoryId(@Param("categoryId") Long categoryId,
such simple queries should be handled by proper method naming, please recheck work without them and fix just the naming method if required

2023-09-28 10:38 UTC, okuzan requested changes

2023-09-28 10:38 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/cartitem/CartItemService.java
> +
```suggestion
```

2023-09-28 10:38 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/user/impl/UserServiceImpl.java
> +                () -> new RuntimeException("Can`t find user with according email"
don't use generic runtime exception

2023-09-28 10:38 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +    private ShoppingCart registerNewCart(User user) {
duplicated method in two services

2023-09-28 10:38 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/cartitem/impl/CartItemServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Can`t find cart by ID : " + id));
```suggestion
```

2023-09-28 10:38 UTC, okuzan commented on src/main/java/spring/boot/bookstore/service/cartitem/impl/CartItemServiceImpl.java
> +    public CartItemResponseDto update(UpdateQuantityDto updateQuantityDto, Long id) {
check if quantity is positive

2023-10-01 12:44 UTC, merged